import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "OCWA Data App",
  description: "Generated by Syed Hassan for OCWA",
  icons: {
    icon: ["/assets/favicons/favicon.ico?v=4"],
    apple: ["/assets/favicons/apple-touch-icon.png?v=4"],
    apple: ["/assets/favicons/apple-touch-icon.png"]
  }
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
